-- Ported from Plus Everything (same author) for Azeroth Almanac's quality-of-life helpers.
-- Wings & Whispers: the creatures who fly you around Azeroth. Written for Azeroth Almanac.
-- Each creature: { key, name, title, bio, facts, again, land }
--   A line is either a string (fine for everyone) or { spicy, family } (family-friendly alternative).
--   {n} = how many times you've flown with them, {time} = flight time, {to} = where you're going.
local _, A = ...
local ns = A.QoL

ns.FlightCrew = {

gryphon = {
	{ "reginald", "Sir Reginald Flapsworth III", "The Unflappable",
		"Ex-Royal Guard mount, retired after an incident with a Dalaran fountain he refuses to discuss.",
		{ "He's carried 4,812 adventurers and only dropped two. Both gnomes. Both fine. Mostly.",
		  { "He insists on being called 'Sir'. He was knighted by a very drunk dwarf in 3 seconds flat.", "He insists on being called 'Sir'. He was knighted by a dwarf who misread the ceremony scroll." },
		  "His feathers are groomed daily by a personal valet named Clive. Clive is a squirrel." },
		{ "Sir Reginald again. Ride #{n}. He's pretending not to remember you. He remembers you.",
		  "Ride #{n} with Sir Reginald. He nods at you exactly once. That's affection, for him." },
		{ "Sir Reginald lands with the grace of a dropped anvil. {time} in the air. He prefers his tips in fish.",
		  "Touchdown in {to}. Sir Reginald bows. You are expected to bow back." } },
	{ "beaksley", "Beaksley", "The Anxious",
		"Apologizes to every cloud he flies through. Has a nervous twitch near wizards.",
		{ "He once flew a whole route backwards because he was too polite to correct the flight master.",
		  { "Under stress he sheds feathers. And other things. Look down at your own risk.", "Under stress he sheds feathers. Lots of feathers. You'll be finding them for weeks." },
		  "His therapist is a very patient owl in Darnassus. Long-distance sessions." },
		{ "Beaksley again! Ride #{n}. He says sorry for last time. Nothing happened last time.",
		  "Ride #{n}. Beaksley is so glad it's you. He was worried it would be a mage." },
		{ "Beaksley lands, says sorry to the ground, and flops over. {time}. You did great, buddy.",
		  "Safe in {to}. Beaksley is breathing into a paper bag. That's normal." } },
	{ "gertrude", "Big Gertrude", "The Ironforge Belter",
		"Raised in a Thunderbrew stable. Sings sea shanties at altitude. Badly. Loudly.",
		{ { "She can drink three dwarves under the table and fly home. The dwarves can't.", "She can out-sing three dwarves and still fly home. The dwarves need a nap." },
		  "Her favorite song has 47 verses. You'll hear about 31 of them today.",
		  { "She once flirted with a mountain. The mountain did not respond. She considers it playing hard to get.", "She once tried to befriend a mountain. It was a quiet friendship." } },
		{ "Gertrude! Ride #{n}! She's already on verse four.",
		  "Ride #{n}. Gertrude remembers you. She remembers everyone who doesn't complain about the singing." },
		{ "Gertrude belts out the final verse as she lands in {to}. {time}. Your ears will recover.",
		  "Landed. Gertrude bows to an audience of zero. {time} of pure art." } },
	{ "twoales", "Talon 'Two-Ales' McGrath", "Steadiest After Two",
		"Flies better after two ales. Crashes after three. Today he's had... let's say two.",
		{ { "He has a strict 'two ales before takeoff' policy, for steadiness. The third is for landing.", "He has a strict 'two snacks before takeoff' policy, for energy. The third snack is for landing." },
		  "His record: Ironforge to Stormwind without a single loop-de-loop. He was very proud.",
		  "He keeps a small flask strapped under his left wing. Do not ask about the flask." },
		{ "Talon again. Ride #{n}. He smells faintly of hops. That's fine. That's fine.",
		  "Ride #{n} with Talon. He gives you a wink. Hold on tight." },
		{ "Talon lands in {to} in one piece. {time}. He's calling that a win.",
		  "{time} and only one tiny barrel roll. Talon's best flight this week." } },
	{ "featherbottom", "Lady Featherbottom", "The Fashionable",
		"Wears a little silk scarf. Judges your transmog silently, then out loud.",
		{ { "She's turned down marriage proposals from four gryphons and one confused hippogryph.", "She's had fan mail from four gryphons and one confused hippogryph." },
		  "She considers mismatched armor a personal insult to her as a bird.",
		  "Her scarf was a gift from a Stormwind noble. She will not say which one. Wink." },
		{ "Lady Featherbottom again. Ride #{n}. She notes you're still wearing that.",
		  "Ride #{n}. Lady Featherbottom adjusts her scarf. She remembers your boots. Unfortunately." },
		{ "Lady Featherbottom lands in {to} and fixes her scarf. {time}. Please change before your next flight.",
		  "{time} of elegance. Lady Featherbottom expects compliments on the landing." } },
	{ "thudd", "Thudd", "Strong, Silent, Single",
		"Says nothing. Flies straight. Has the thighs of a demigod.",
		{ { "The other gryphons call him 'Thunder Thighs'. He's never once denied it.", "The other gryphons call him 'Thunder Wings'. He has never once argued." },
		  "He has said exactly one word in his whole life. It was 'no'. To a gnome engineer.",
		  "He can carry a tauren. He has. The tauren cried a little. Happy tears." },
		{ "Thudd. Ride #{n}. He nods. That's the whole conversation.",
		  "Ride #{n} with Thudd. He blinks slowly. Out of respect, probably." },
		{ "Thudd lands in {to} like a falling mountain. {time}. Gentle, for him.",
		  "{time}. Thudd lands, nods, and stares at the horizon." } },
	{ "pip", "Pip", "Smallest Gryphon on the Roster",
		"Technically a juvenile. Technically not licensed. Technically you're already in the air.",
		{ "Pip's flight license is a drawing of a gryphon in crayon. The flight master accepted it.",
		  { "He's still going through 'the molt'. Things fall off. Don't take it personally.", "He's still growing in his adult feathers. Some are... experimental." },
		  "He's convinced he'll grow up to be a dragon. Nobody has the heart to tell him." },
		{ "Pip again! Ride #{n}! He's grown a whole inch. He'd like you to notice.",
		  "Ride #{n}. Pip is SO excited. Too excited. Hold the reins." },
		{ "Pip lands in {to}! Mostly on the landing pad! {time}! He did it!",
		  "{time}. Pip landed. He'd like a sticker." } },
	{ "honk", "Honk", "Probably a Goose",
		"The flight master swears Honk is a gryphon. Honk has webbed feet and honks.",
		{ "Honk has never been seen to lay an egg. Honk has never been seen NOT to steal bread.",
		  { "Honk bit a paladin on the bum during the Second War. The paladin still won't sit on that side.", "Honk bit a paladin during the Second War. The paladin still flinches at geese." },
		  "Every gryphon in the aerie is afraid of Honk." },
		{ "HONK. Ride #{n}. Honk remembers the bread you didn't give him.",
		  "Ride #{n}. HONK. (He's happy to see you. Probably.)" },
		{ "Honk lands in {to} and immediately chases a guard. {time}.",
		  "{time}. HONK. You've arrived." } },
	{ "duchess", "The Duchess", "Retired Racing Champion",
		"Won the Westfall Derby three years running. Has never slowed down since.",
		{ "Her trophy room is a cave full of shiny things. Some of them are trophies.",
		  { "She had a scandalous affair with a racing wind rider. Cross-faction. The aerie still whispers.", "She had a famous rivalry with a racing wind rider. Cross-faction. Legendary." },
		  "She thinks other flights are 'for tourists'." },
		{ "The Duchess. Ride #{n}. She's already annoyed you didn't pick the express route.",
		  "Ride #{n}. The Duchess is in a hurry. She's always in a hurry." },
		{ "The Duchess lands in {to} in {time}. She'd like you to know she was holding back.",
		  "{time}. The Duchess is already looking for her next passenger." } },
	{ "barnaby", "Barnaby", "Professional Gossip",
		"Knows everybody's business. Shares everybody's business. Mid-flight.",
		{ { "He knows which Stormwind noble is sneaking off to Goldshire at night. He'll tell you for a fish.", "He knows which Stormwind noble keeps a secret pet murloc. He'll tell you for a fish." },
		  "He once knew about a plot against the king before SI:7 did. He was too busy gossiping to report it.",
		  "He has a little notebook. You're in it now." },
		{ "Barnaby again. Ride #{n}. Did you hear about the innkeeper? You WILL hear about the innkeeper.",
		  "Ride #{n}. Barnaby's got new gossip. It's about you." },
		{ "Barnaby lands in {to} mid-sentence. {time}. You'll never know how that story ended.",
		  "{time}. Barnaby promises to tell you the rest next time. He won't." } },
	{ "stormbeak", "Stormbeak", "Flies Through Weather, On Purpose",
		"Loves storms. Loves lightning. Loves being slightly on fire.",
		{ "He's been struck by lightning nine times. He says the tenth one is the charm.",
		  "His feathers stand on end permanently. Gnomes use him to test static.",
		  { "He calls thunder 'the sky's way of flirting with him'.", "He calls thunder 'the sky saying hello'." } },
		{ "Stormbeak again. Ride #{n}. He's looking at a cloud. Please don't let him go to the cloud.",
		  "Ride #{n} with Stormbeak. Your hair is already standing up." },
		{ "Stormbeak lands in {to}, crackling. {time}. Don't touch anything metal for a bit.",
		  "{time}. Stormbeak is disappointed there wasn't lightning. You're not." } },
	{ "mortimer", "Mortimer", "Former Siege Gryphon",
		"Flew bombing runs in the Second War. Still drops things when he gets nervous.",
		{ "He has a medal. He wears it everywhere. It's a bottle cap.",
		  { "Old habits: he drops 'payloads' over enemy camps. Payloads are not always bombs.", "Old habits: he still dives at anything that looks like an orc camp." },
		  "He tells the same war story every flight. It gets bigger every time." },
		{ "Mortimer! Ride #{n}! Have you heard the one about Grim Batol? (Yes. Ride #{n} times.)",
		  "Ride #{n}. Mortimer salutes you. With a wing. Carefully." },
		{ "Mortimer lands in {to}. {time}. 'Mission accomplished,' he grunts.",
		  "{time}. Mortimer lands and checks the sky for dragons. Old habits." } },
	{ "sunny", "Sunny", "Aggressively Cheerful",
		"Thinks every flight is the best day of her life. It's exhausting.",
		{ "She has never had a bad day. Scientists in Ironforge are studying her.",
		  "She names every cloud. She's named over 8,000 clouds.",
		  { "She hugs everyone after landing. Even the Defias. Especially the Defias.", "She hugs everyone after landing. Everyone. No exceptions." } },
		{ "SUNNY! Ride #{n}! She's never been happier! (She says that every time.)",
		  "Ride #{n}. Sunny squeals. You hear it in your bones." },
		{ "Sunny lands in {to}: 'BEST FLIGHT EVER!' {time}. She means it every time.",
		  "{time}. Sunny insists on a hug. Resistance is futile." } },
	{ "grimfeather", "Grimfeather", "Brooding Poet",
		"Writes dark poetry about the void between the clouds. Wears black feathers 'ironically'.",
		{ "His best poem: 'The Sky Is Merely A Floor We Have Not Fallen Through Yet.'",
		  { "He's had his heart broken by every hen in the aerie. He's been told it's the poetry.", "Every gryphon in the aerie has heard his poetry. Many twice. Against their will." },
		  "He sighs dramatically on every turn." },
		{ "Grimfeather. Ride #{n}. He sighs. You sigh. It's a vibe.",
		  "Ride #{n}. Grimfeather has written a new poem. About you. It's sad." },
		{ "Grimfeather lands in {to}. 'All journeys end,' he whispers. {time}.",
		  "{time}. Grimfeather lands, then stares meaningfully into the distance." } },
	{ "chomp", "Chomp", "Always Hungry",
		"Eats anything. Has eaten saddles. Has eaten a passenger's boot. Mid-flight.",
		{ "He once ate an entire Westfall Stew. The bowl too. The cook too, briefly.",
		  { "His digestion is legendary. Gryphons downwind of him wear masks.", "He gets the hiccups after big meals. They're loud. Very loud." },
		  "If you have food in your bags, he knows." },
		{ "Chomp again! Ride #{n}. He's sniffing your bags. He knows.",
		  "Ride #{n}. Chomp licks your boot. Hello to you too." },
		{ "Chomp lands in {to} and goes straight for the vendor. {time}.",
		  "{time}. Chomp lands and asks, with his eyes, for a snack." } },
	{ "orville", "Orville", "Navigator Who Doesn't Use a Map",
		"Has a fantastic sense of direction. Allegedly. Has never been lost. Allegedly.",
		{ "He once flew to Booty Bay when asked for Menethil. He says Booty Bay was the 'scenic route'.",
		  "He says the stars guide him. He's never once looked at them.",
		  "He has a cousin who's a compass. They don't talk." },
		{ "Orville. Ride #{n}. He's very confident about where you're going. Too confident.",
		  "Ride #{n}. Orville says 'shortcut'. Brace yourself." },
		{ "Orville lands in {to}! The correct place! {time}! He's as surprised as you!",
		  "{time}. You're in {to}. Orville would like to thank the stars." } },
	{ "baroness", "Baroness von Wingsworth", "Old Money",
		"Descended from the gryphon that carried King Llane once. She brings it up. Often.",
		{ "Her nest has velvet. She sleeps on a gold pillow. The pillow is a gold bar.",
		  { "She's been married four times. Each husband was 'a little too common'.", "She has four noble titles. She uses all four. Every time." },
		  "She considers peasants 'charming, in small doses'." },
		{ "The Baroness again. Ride #{n}. She's polite. Coldly polite.",
		  "Ride #{n}. The Baroness remembers you. She doesn't remember your name." },
		{ "The Baroness lands in {to}. {time}. She expects you to dismount on the left side.",
		  "{time}. The Baroness lands and waits for someone to bring her tea." } },
	{ "flint", "Flint", "Mining Gryphon",
		"Grew up near Thelsamar. Can smell copper from a mile up. Gets distracted by every vein.",
		{ "He's found more copper than any miner in Loch Modan. He just can't mine it.",
		  "He'll dive if he sees a mithril vein. You've been warned.",
		  { "Dwarven miners call him the 'gold digger'. He doesn't deny it.", "Dwarven miners call him the 'treasure nose'. He's very proud." } },
		{ "Flint again. Ride #{n}. He just spotted tin. Hold on.",
		  "Ride #{n}. Flint's nose is twitching. Ore nearby." },
		{ "Flint lands in {to} after only two detours. {time}.",
		  "{time}. Flint lands, sniffs, sighs. No ore here." } },
	{ "wobbles", "Wobbles", "Has a Bad Wing",
		"Flies slightly sideways. Always has. Always will. Gets there anyway.",
		{ "His left wing flaps 10% harder. Engineers call it 'the Wobbles Correction'.",
		  "He's never crashed. He has 'arrived dramatically' 43 times.",
		  { "He tells the ladies the limp is from a dragon fight. It was a door.", "He tells everyone the limp is from a dragon fight. It was a door." } },
		{ "Wobbles! Ride #{n}! You lean left without being told. You're a pro.",
		  "Ride #{n}. Wobbles wobbles. You wobble too. Teamwork." },
		{ "Wobbles arrives in {to}, dramatically. {time}. Everyone is fine.",
		  "{time}. Wobbles lands at a 30 degree angle. Close enough." } },
	{ "maple", "Maple", "Retired Mail Carrier",
		"Used to fly the mail between Stormwind and Ironforge. Still delivers things nobody asked for.",
		{ "She has read every letter she ever carried. She has opinions about your aunt.",
		  { "She's delivered more love letters than anyone in Azeroth. She has notes on all of them.", "She's delivered thousands of letters. She remembers all the best birthday cards." },
		  "She still wears her little postal hat." },
		{ "Maple again. Ride #{n}. She has a letter for you. It's a coupon.",
		  "Ride #{n}. Maple asks if you've written home lately." },
		{ "Maple drops you off in {to}. {time}. Signature required. (She's kidding. Probably.)",
		  "{time}. Delivered. Maple stamps your forehead. Lightly." } },
},

windrider = {
	{ "grumthak", "Grumthak the Unbathed", "Proud of His Smell",
		"Hasn't bathed since the Second War. Considers it a cultural tradition.",
		{ { "His smell has its own name in Orcish. It translates roughly to 'courage'.", "His smell has its own name in Orcish. It translates to 'character'." },
		  "Flies are afraid of him. Other flies.",
		  "He once won a staring contest against a kodo. The kodo fainted. From the smell." },
		{ "Grumthak. Ride #{n}. You smell him before you see him.",
		  "Ride #{n}. Grumthak greets you. Your eyes water." },
		{ "Grumthak lands in {to}. {time}. Please wash your armor.",
		  "{time}. Grumthak lands. Nearby plants wilt slightly." } },
	{ "zephyra", "Zephyra", "Motivational Speaker",
		"Aggressively positive. Tells you to believe in yourself at 300 feet.",
		{ "Her catchphrase: 'You're not falling, you're FLYING with extra steps!'",
		  "She runs a weekly self-help circle for nervous wind riders. Attendance: one. Beaksley. He's lost.",
		  { "She once motivated a grunt so hard he proposed to her. She said 'believe in yourself, not in me'.", "She once motivated a grunt so hard he took up knitting. He's very happy now." } },
		{ "Zephyra! Ride #{n}! She's PROUD of you for coming back!",
		  "Ride #{n}. Zephyra believes in you. Loudly." },
		{ "Zephyra lands in {to}: 'You DID that!' {time}. You sort of did.",
		  "{time}. Zephyra gives you a wing-five." } },
	{ "oldtusk", "Old Tusk", "Has Opinions About Goblins",
		"Has a lot of opinions about goblins and will share all of them, in order.",
		{ "He was once paid in goblin coins. They turned out to be painted rocks. He has never forgiven them.",
		  { "He has a goblin-shaped bite mark on his tail. The goblin has a wind-rider-shaped one on his everything.", "He and a goblin once had a feud over a parking spot. It lasted eleven years." },
		  "He'll fly you to Ratchet. He'll complain the whole way." },
		{ "Old Tusk. Ride #{n}. He picks up his goblin rant right where he left off.",
		  "Ride #{n}. Old Tusk asks if you're a goblin. You are not. He checks again." },
		{ "Old Tusk lands in {to}. {time}. 'At least it's not Ratchet,' he mutters.",
		  "{time}. Old Tusk spits on a goblin-shaped rock and leaves." } },
	{ "scarwing", "Scarwing", "Veteran of a Hundred Raids",
		"Covered in scars. Every one has a story. Every story ends with 'and then I bit him'.",
		{ "He once bit a dragonkin's tail clean off. He still has it. It's his pillow.",
		  { "He has a scar in a very awkward place. He says it was a lucky crossbow bolt. The bolt was lucky.", "He has a scar shaped like Kalimdor. He claims it's a map." },
		  "He's carried three different Horde heroes to three different victories. He takes 40% of the credit." },
		{ "Scarwing again. Ride #{n}. He shows you a new scar. It's from a door.",
		  "Ride #{n}. Scarwing growls. That's his happy growl." },
		{ "Scarwing lands in {to}. {time}. 'Lok'tar,' he grunts.",
		  "{time}. Scarwing lands hard. On purpose. For the Horde." } },
	{ "nibblet", "Nibblet", "Teething",
		"A young wind rider who chews everything. The reins. The saddle. Your leg, gently.",
		{ "He's chewed through 64 saddles this year. The tauren saddle-maker has bought a house.",
		  { "His stinger isn't fully grown yet. He's very self-conscious about his size.", "His stinger isn't fully grown yet. He practices looking scary in puddles." },
		  "He thinks your boots are snacks." },
		{ "Nibblet! Ride #{n}! He's already chewing your stirrup.",
		  "Ride #{n}. Nibblet nibbles. It's how he says hello." },
		{ "Nibblet lands in {to} with half your saddle in his mouth. {time}.",
		  "{time}. Nibblet lands and gives you back your glove. Damp." } },
	{ "duskmane", "Duskmane", "The Night Flyer",
		"Prefers flying at night. Sees perfectly in the dark. Sees things you'd rather he didn't.",
		{ { "He's seen what goes on behind the Orgrimmar inn after midnight. He's taking it to the grave.", "He's seen every secret meeting in Orgrimmar. He tells nobody. Mostly." },
		  "His eyes glow in the dark. It's useful. It's also creepy.",
		  "He hums trollish lullabies. He learned them from a witch doctor. Don't sleep." },
		{ "Duskmane. Ride #{n}. He knows things about you now.",
		  "Ride #{n}. Duskmane's eyes glint. He remembers." },
		{ "Duskmane lands in {to} without a sound. {time}. Spooky.",
		  "{time}. Duskmane lands and vanishes into the shadows. Show-off." } },
	{ "ruffles", "Ruffles", "Fluffiest Wind Rider",
		"Has a mane like a lion that got caught in a storm. Takes hours to brush.",
		{ "She has her own hairdresser in Thunder Bluff. The hairdresser is a very patient tauren named Moo.",
		  { "She says she's single because the other wind riders 'can't handle all this volume'.", "She has won 'Best Mane' at the Thunder Bluff fair nine years running." },
		  "Static from her mane once powered a goblin lamp for a week." },
		{ "Ruffles again! Ride #{n}. You're now 20% covered in fluff.",
		  "Ride #{n}. Ruffles' mane is extra big today. She'd like you to notice." },
		{ "Ruffles lands in {to}, fabulous. {time}. You'll be picking fluff out of your armor until next week.",
		  "{time}. Ruffles fluffs her mane and poses for nobody." } },
	{ "grunt", "Grunt", "Literally Named Grunt",
		"His trainer had no imagination. Grunt has no complaints. Grunt has no thoughts at all, really.",
		{ "His favorite food is 'yes'. His favorite color is 'flying'.",
		  { "He once mistook a tauren's tail for his girlfriend. They're still friends.", "He once mistook a tauren's tail for a snake and attacked it. They're still friends." },
		  "He's the most reliable flyer in Orgrimmar. There's nothing in there to go wrong." },
		{ "Grunt. Ride #{n}. Grunt grunts.",
		  "Ride #{n}. Grunt. Grunt." },
		{ "Grunt lands in {to}. {time}. Grunt.",
		  "{time}. Grunt has landed. Grunt is happy. Grunt." } },
	{ "sizzle", "Sizzle", "Allergic to Durotar Sand",
		"Sneezes constantly. Every sneeze is a small earthquake. You're flying through Durotar.",
		{ "She's sneezed a passenger off twice. Both landed in the Valley of Trials. Both became heroes.",
		  { "Her sneezes come out both ends. Hold your breath.", "Her sneezes knock pebbles off cliffs. Hold on tight." },
		  "A shaman once tried to cure her. Now he sneezes too." },
		{ "Sizzle again. Ride #{n}. Bless you. Bless you. Bless you.",
		  "Ride #{n}. Sizzle is sniffly. Wipe your saddle." },
		{ "Sizzle lands in {to} mid-sneeze. {time}. Gesundheit.",
		  "{time}. Sizzle lands and sneezes once, for luck." } },
	{ "krasha", "Krasha the Bold", "Ex-Arena Fighter",
		"Fought in the Ring of Valor for a decade. Thinks every landing is a fight.",
		{ "She has 312 wins and 1 loss. The loss was to a very determined squirrel.",
		  { "She still flexes at other wind riders when she lands. The males faint. Some females too.", "She still flexes at other wind riders when she lands. Everyone claps. Nervously." },
		  "She's banned from the Gadgetzan arena for biting the referee." },
		{ "Krasha! Ride #{n}. She cracks her neck. Let's go.",
		  "Ride #{n}. Krasha winks at you. Like a champion." },
		{ "Krasha lands in {to} like she just won a title fight. {time}.",
		  "{time}. Krasha lands and roars at a passing guard. For practice." } },
	{ "uncle", "Uncle Gazzik", "Tells Dad Jokes",
		"Every flight, a new dad joke. Every joke, a new low.",
		{ "His best joke: 'Why did the orc bring a ladder to the raid? He heard the boss was high level.'",
		  { "He once told a joke so bad a troll took off his own head. Trolls regenerate, it's fine.", "He once told a joke so bad a whole raid wiped. Out of shame." },
		  "He has 800 jokes. He tells number 17 the most." },
		{ "Uncle Gazzik again. Ride #{n}. He's got a new one. It's the old one.",
		  "Ride #{n}. Uncle Gazzik clears his throat. Here it comes." },
		{ "Uncle Gazzik lands in {to}: 'That was a PLANE good flight!' {time}. There are no planes here.",
		  "{time}. Uncle Gazzik laughs at his own joke for the rest of the landing." } },
	{ "shadowfang", "Shadowfang", "Edgelord",
		"Insists on being called by his full name. Wears spiked armor. Has never been in a fight.",
		{ "His spikes are made of painted wood. Don't tell him you know.",
		  { "He writes his name in the sand with his tail. He also writes 'Shadowfang + ?' with a little heart.", "He writes his name in the sand with his tail. In a very cool font." },
		  "He's afraid of rabbits." },
		{ "Shadowfang. Ride #{n}. He growls. It's a squeaky growl.",
		  "Ride #{n}. Shadowfang tries to look menacing. Adorable." },
		{ "Shadowfang lands in {to} and strikes a pose. {time}. Nobody noticed.",
		  "{time}. Shadowfang lands, sees a rabbit, takes off again." } },
	{ "mellow", "Mellow", "Very, Very Chill",
		"Takes the scenic route. Always. Has never hurried in his life.",
		{ "He was raised by a tauren druid. Vibes only.",
		  { "He chews a mysterious herb from Feralas. He's very relaxed. Very.", "He chews peacebloom leaves. He's very relaxed. Very." },
		  "His top speed is 'eh'." },
		{ "Mellow. Ride #{n}. No rush, man.",
		  "Ride #{n}. Mellow yawns. You yawn. The world slows down." },
		{ "Mellow drifts into {to} in {time}. Whoa. That was, like, a journey.",
		  "{time}. Mellow lands so gently you don't notice you've landed." } },
	{ "beezlebub", "Beezlebub", "Stinger Enthusiast",
		"Extremely proud of his stinger. Polishes it daily. Talks about it constantly.",
		{ { "He'll tell you his stinger is 'above average'. Repeatedly. Unprompted.", "He'll tell you his stinger is the shiniest in Kalimdor. Repeatedly." },
		  "He uses it to open letters. And jars. And doors. He's very proud.",
		  "He entered it in the Darkmoon Faire. It won a ribbon. Participation." },
		{ "Beezlebub again. Ride #{n}. He's polished his stinger for you. How thoughtful.",
		  "Ride #{n}. Beezlebub shows you his stinger. Again." },
		{ "Beezlebub lands in {to} and buffs his stinger. {time}.",
		  "{time}. Beezlebub lands, stinger-first. Stylish." } },
	{ "honeypaw", "Honeypaw", "Loves Beehives",
		"Will fly hundreds of yards off course for a beehive. Has been stung 4,000 times. Worth it.",
		{ "Her face is permanently a bit puffy. She calls it 'her glow'.",
		  { "She'll do anything for honey. Anything. Don't ask the beekeeper in Mulgore what happened.", "She'll do anything for honey. She once traded a whole saddle for a jar." },
		  "She hums. Bees think she's one of them." },
		{ "Honeypaw. Ride #{n}. She smells like honey and bad decisions.",
		  "Ride #{n}. Honeypaw is sticky. Everything is sticky." },
		{ "Honeypaw lands in {to}. {time}. Something is buzzing in your hood.",
		  "{time}. Honeypaw lands next to a flower bed. Coincidence? No." } },
},

hippogryph = {
	{ "moonfeather", "Moonfeather", "Writes Terrible Poetry",
		"Recites her own poetry at altitude. You can't escape. You're 400 feet up.",
		{ "Her latest work: 'Ode to a Moonwell (Part 14)'. There are 40 parts.",
		  { "Her love poems are so steamy the druids banned them from the Cenarion Circle library.", "Her poems are so long the druids gave them their own tree." },
		  "She rhymes 'Teldrassil' with 'pretty basil'. Every time." },
		{ "Moonfeather. Ride #{n}. She's on part 15 now.",
		  "Ride #{n}. Moonfeather clears her throat. Poetry incoming." },
		{ "Moonfeather lands in {to} on the last line of a sonnet. {time}. It didn't rhyme.",
		  "{time}. Moonfeather bows. She expects snapping, not clapping." } },
	{ "sylvanthra", "Lady Sylvanthra", "Thinks She's an Elf Princess",
		"Believes she's a night elf princess cursed into a hippogryph. She is not.",
		{ "She wears a tiny tiara. It's a bottle cap. Don't tell her.",
		  { "She's waiting for a handsome druid to kiss her and break the curse. Several have tried. No curse.", "She's waiting for a handsome druid to break her curse. She'll wait forever." },
		  "She insists you call her 'Your Highness'." },
		{ "Her Highness again. Ride #{n}. You may approach.",
		  "Ride #{n}. Lady Sylvanthra holds out a wing to be kissed. You don't have to." },
		{ "Lady Sylvanthra lands in {to}. {time}. 'Thou art dismissed.'",
		  "{time}. Her Highness has landed. Bow." } },
	{ "breezy", "Breezy", "Loves the Wind",
		"Flies with her beak wide open. Loves the wind in her face. Has eaten 40 bugs today.",
		{ "She once flew so fast she caught a bat. The bat was surprised. So was she.",
		  { "She's a bit of a free spirit. Nests with whoever's warmest. Today it might be you.", "She's a bit of a free spirit. She once followed a butterfly to Feralas." },
		  "She's never closed her beak. Not once. Druids are concerned." },
		{ "Breezy! Ride #{n}! WHEEEEEE!",
		  "Ride #{n}. Breezy's beak is already open. Bugs, beware." },
		{ "Breezy lands in {to}, panting happily. {time}. She caught 12 bugs.",
		  "{time}. Breezy lands and immediately wants to go again." } },
	{ "starwhisker", "Starwhisker", "Astrologer",
		"Reads your future in the stars. Your future is always 'a long flight'.",
		{ "She predicted the Third War. She also predicted rain for 4,000 days straight. One of those came true.",
		  { "She'll read your love life in the stars. Spoiler: it's 'complicated'.", "She'll read your luck in the stars. Spoiler: you'll find a grey item." },
		  "Her horoscopes are printed in the Darnassus Daily. Nobody reads them." },
		{ "Starwhisker. Ride #{n}. The stars said you'd come back.",
		  "Ride #{n}. Starwhisker squints at the sky. 'Ah. You again.'" },
		{ "Starwhisker lands in {to}. {time}. 'The stars foresaw this exact landing.'",
		  "{time}. Starwhisker lands and predicts a good loot roll. No promises." } },
	{ "thistle", "Thistle", "Grumpy Old Hippogryph",
		"Has been flying since before the Sundering. Allegedly. Remembers when Teldrassil was a sapling.",
		{ "He complains that 'young hippogryphs don't flap like they used to'.",
		  { "He once dated Malfurion's hippogryph. 'Different times,' he says.", "He once flew with Malfurion's hippogryph. 'Different times,' he says." },
		  "His knees crack every time he lands. It sounds like a branch breaking." },
		{ "Thistle. Ride #{n}. 'Back in my day...' Here we go.",
		  "Ride #{n}. Thistle grumbles. That means he's fond of you." },
		{ "Thistle lands in {to}. Crack. {time}. His knees, not the ground.",
		  "{time}. Thistle lands and demands a nap." } },
	{ "dewdrop", "Dewdrop", "Very Shy",
		"Hides behind her own wings. Will only fly if nobody looks at her.",
		{ "She's the fastest hippogryph in Ashenvale. Nobody's seen it, because she won't race if watched.",
		  { "She has a huge crush on a stag in Moonglade. She's never said a word to him. He's a stag.", "She has a best friend in Moonglade. It's a mushroom. They're very close." },
		  "Please don't look directly at her." },
		{ "Dewdrop. Ride #{n}. Don't look at her. She knows you're looking.",
		  "Ride #{n}. Dewdrop peeks out from her wing. Hi." },
		{ "Dewdrop lands in {to} and hides behind the flight master. {time}.",
		  "{time}. Dewdrop landed. Shh. Don't make a fuss." } },
	{ "rumble", "Rumble", "Big Boy",
		"The biggest hippogryph in Darkshore. Shakes the ground when he walks. Gentle as a kitten.",
		{ "He's scared of squirrels. Sentinels have to escort him past trees.",
		  { "His landings register on goblin seismographs. And make the nearby kaldorei blush. It's the bounce.", "His landings register on goblin seismographs in Ratchet." },
		  "He once sat on a gnoll by accident. The gnoll gave up mercenary work." },
		{ "Rumble! Ride #{n}! The ground trembles in welcome.",
		  "Ride #{n}. Rumble nuzzles you. You fall over. Gently." },
		{ "Rumble lands in {to}. Thoom. {time}. Everyone nearby checks for earthquakes.",
		  "{time}. Rumble lands and a tree drops all its leaves." } },
	{ "glimmer", "Glimmer", "Sparkly",
		"Rolled in moonwell water as a chick. Has glowed faintly ever since.",
		{ "She's used as a nightlight in the Darnassus orphanage.",
		  { "She says the glow makes her 'irresistible under moonlight'. The other hippogryphs agree. Loudly.", "She says the glow makes her 'easy to find at parties'." },
		  "Moths follow her everywhere. Hundreds of moths." },
		{ "Glimmer. Ride #{n}. You're glowing a little too now.",
		  "Ride #{n}. Glimmer sparkles. So do you, slightly." },
		{ "Glimmer lands in {to}, glittering. {time}. Moths incoming.",
		  "{time}. Glimmer lands and lights up the whole flight pad." } },
	{ "sentinel", "Sentinel Swiftwing", "All Business",
		"Ex-military. Salutes. Flies at exactly regulation speed. No small talk.",
		{ "She's never smiled. Officially. There are rumors from a party in 2004.",
		  { "She's escorted Tyrande. She won't talk about it. She blushes a bit when she doesn't talk about it.", "She's escorted Tyrande. She won't talk about it. It's classified." },
		  "Her feathers are arranged in regulation order." },
		{ "Sentinel Swiftwing. Ride #{n}. She salutes. You salute back.",
		  "Ride #{n}. Swiftwing checks your posture. Sit up straight." },
		{ "Sentinel Swiftwing lands in {to}. {time}. Exactly on schedule.",
		  "{time}. Landed. Swiftwing salutes. Dismissed." } },
	{ "puddle", "Puddle", "Afraid of Water",
		"A hippogryph who lives on islands. Afraid of water. Flies very, very high over the sea.",
		{ "She once saw a murloc and flew home to Teldrassil in 30 seconds flat.",
		  { "She'll only take a bath if she's been VERY naughty. She's never had a bath.", "She takes a dust bath instead. It's not the same. Nobody tells her." },
		  "Her name was a joke. She didn't get it. She still doesn't." },
		{ "Puddle again. Ride #{n}. She's flying a bit high. Because of the sea.",
		  "Ride #{n}. Puddle eyes the ocean nervously." },
		{ "Puddle lands in {to}, far away from any water. {time}.",
		  "{time}. Puddle lands and checks for puddles. None. Phew." } },
},

bat = {
	{ "flappula", "Count Flappula", "Drama Queen of the Night",
		"Dramatic. Hates garlic and daylight. Loves gossip and a good cape.",
		{ "He's been 'dying' of the sun for 200 years. It's overcast in Tirisfal.",
		  { "He bites his passengers. 'Just a taste, darling.' It tickles. Mostly.", "He tries to bite his passengers. 'Just to say hello, darling.' He has no teeth left." },
		  "He wears a tiny cape. It's actually just his wing, folded fancy." },
		{ "Count Flappula! Ride #{n}! 'Ah, my favorite neck.'",
		  "Ride #{n}. Count Flappula swoops in. Bleh. Bleh. Bleh." },
		{ "Count Flappula lands in {to}. {time}. 'Until we meet again, mortal.'",
		  "{time}. The Count bows deeply and hangs from the nearest beam." } },
	{ "nibbles", "Nibbles", "Wants to Bite Something",
		"Just wants to bite something. Anything. Please. Just one bite.",
		{ "He's bitten 3 Forsaken. They didn't notice. They have no blood.",
		  { "He has a little bib. It's never clean. Don't ask.", "He has a little bib. It says 'Bite Me'. He is very literal." },
		  "He asks every passenger, very politely, for a bite." },
		{ "Nibbles. Ride #{n}. 'Just a little one?' No, Nibbles.",
		  "Ride #{n}. Nibbles stares at your arm. Lovingly." },
		{ "Nibbles lands in {to}. {time}. He bites the flight master. Finally.",
		  "{time}. Nibbles lands, sulking. No bites today." } },
	{ "echo", "Echo", "Can't Stop Echolocating",
		"Echolocates constantly. Squeaks every half second. You'll hear it in your dreams.",
		{ "She can find a copper coin in a dark cave from a mile away. She can't find her own nest.",
		  { "She squeaks louder when she's flirting. She's always squeaking very loud around you.", "She squeaks louder when she's happy. She's squeaking very loud right now." },
		  "Apothecaries use her to find lost vials." },
		{ "Echo! Ride #{n}! Squeak! Squeak! Squeak!",
		  "Ride #{n}. Echo squeaks hello. And goodbye. And hello." },
		{ "Echo lands in {to}. Squeak. {time}. Squeak.",
		  "{time}. Echo lands. One last squeak. Okay, two." } },
	{ "mortis", "Mortis", "Undead Bat",
		"A Forsaken bat. Bits fall off. Bits get sewn back on. Flies surprisingly well.",
		{ "His left wing is from a different bat. They don't get along.",
		  { "He's lost his tail three times. He says he's 'great at losing things in all the wrong places'.", "He's lost his tail three times. The apothecaries keep spares." },
		  "He doesn't need to breathe. He still sighs dramatically." },
		{ "Mortis again. Ride #{n}. Is that a new ear? It is a new ear.",
		  "Ride #{n}. Mortis creaks. Something rattles." },
		{ "Mortis lands in {to}. A toe falls off. {time}. He'll get it later.",
		  "{time}. Mortis lands and checks he's still all there." } },
	{ "duchessbat", "Duchess Velvetwing", "Refined Bat",
		"Sophisticated. Hangs upside-down at tea time. Judges you upside-down.",
		{ "She drinks blood from a crystal goblet. Pinky out.",
		  { "She's had a long, scandalous affair with a gargoyle. Very stony romance.", "She has a pen pal who's a gargoyle. Very stony letters." },
		  "She sings opera. Only bats can hear it. You're lucky." },
		{ "Duchess Velvetwing. Ride #{n}. She looks at you. Upside-down. Disapprovingly.",
		  "Ride #{n}. The Duchess sniffs. You're acceptable, barely." },
		{ "Duchess Velvetwing lands in {to}. {time}. She expects a thank-you note.",
		  "{time}. The Duchess lands and hangs upside-down from your shoulder pad." } },
	{ "squeakers", "Squeakers", "Tiny, Furious",
		"The smallest bat on the Forsaken roster. The angriest creature in Lordaeron.",
		{ "He once fought off a whole Scarlet patrol. They were laughing too hard to fight back.",
		  { "He's got a big attitude for a small bat. Says it's not the size of the wings, it's the fury.", "He's got a big attitude for a small bat. 'It's not the size, it's the fury.'" },
		  "Nobody knows how he carries anyone. Including him." },
		{ "Squeakers! Ride #{n}! He's furious about it!",
		  "Ride #{n}. Squeakers glares at you. Tiny, mighty glare." },
		{ "Squeakers lands in {to}, panting with rage. {time}. He did it. He's still mad.",
		  "{time}. Squeakers lands and challenges a guard to a duel." } },
	{ "batrick", "Batrick", "Party Bat",
		"Thinks every flight is a party. Brings tiny hats. You'll wear the hat.",
		{ "He's been to every Undercity party since the Scourge. He's the only one who remembers them.",
		  { "He once woke up in the Royal Quarter wearing nothing but Varimathras's cufflinks.", "He once woke up in the Royal Quarter wearing Varimathras's cufflinks. Nobody knows how." },
		  "His hat collection is bigger than his wingspan." },
		{ "BATRICK! Ride #{n}! Party hat's on the saddle. Put it on.",
		  "Ride #{n}. Batrick blows a tiny party horn." },
		{ "Batrick lands in {to}: 'Afterparty's at the inn!' {time}.",
		  "{time}. Batrick lands and throws confetti. Where did he get confetti?" } },
},

rare = {
	{ "kevin", "Kevin", "Lost Proto-Drake Intern",
		"A proto-drake intern from Northrend who took a wrong turn about four expansions early. No license. Lots of confidence.",
		{ "Kevin isn't supposed to be here. Kevin isn't supposed to exist yet. Kevin doesn't care.",
		  { "Kevin's 'flight training' was one weekend and a lot of energy drinks.", "Kevin's 'flight training' was one weekend and a lot of enthusiasm." },
		  "Kevin will absolutely loop-de-loop. Kevin will not ask first." },
		{ "KEVIN! Ride #{n}! Kevin's still not supposed to be here!",
		  "Ride #{n}. Kevin waves. With a wing. While flying. Concerning." },
		{ "Kevin lands in {to}, upside-down. {time}. 'Nailed it.'",
		  "{time}. Kevin lands near {to}. Ish. Close enough for Kevin." } },
	{ "steve", "Steve", "Dragonhawk From the Wrong Expansion",
		"A blood elf dragonhawk who flew in from somewhere called 'Quel'Thalas'. Nobody's heard of it yet.",
		{ "Steve sets things on fire when he's nervous. Steve is always nervous.",
		  { "Steve's a bit of a show-off. Glowing scales, fancy plumage, enormous ego. Very blood elf.", "Steve is a bit of a show-off. Glowing scales, fancy feathers, fancy everything." },
		  "Steve thinks everyone here is very old-fashioned." },
		{ "Steve! Ride #{n}. Something's smoking. It's the saddle. It's fine.",
		  "Ride #{n}. Steve flicks his tail. Small flame. Oops." },
		{ "Steve lands in {to} in a puff of smoke. {time}. Your eyebrows will grow back.",
		  "{time}. Steve lands and immediately asks where the nearest mage is." } },
	{ "chicken", "Sir Clucksalot", "A Chicken. Somehow.",
		"A regular chicken. Wearing a gryphon costume. Carrying you. Physics has left the building.",
		{ "Nobody knows how a chicken carries an adventurer. The chicken doesn't know either.",
		  { "He's very proud of the costume. He made it himself. The beak is a carrot.", "He's very proud of the costume. He made it himself, out of hope." },
		  "Bawk." },
		{ "Sir Clucksalot! Ride #{n}! Bawk!",
		  "Ride #{n}. Bawk bawk. (He's glad you're back.)" },
		{ "Sir Clucksalot lands in {to}. {time}. He lays an egg. Out of pride.",
		  "{time}. Bawk. You've landed. Somehow." } },
	{ "murky", "Murky", "Murloc on a Kite",
		"A murloc strapped to a kite strapped to your saddle. He's steering. Nobody gave him permission.",
		{ "Mrglglgl. (He says he's done this before. He hasn't.)",
		  { "He's very wet. You'll be very wet. That's the deal with Murky.", "He's very damp. You'll be very damp. That's the deal." },
		  "Murky's only instruction from the flight master was 'don't'." },
		{ "Mrgl! Ride #{n}! Murky's back on the kite!",
		  "Ride #{n}. Murky waves his little fin." },
		{ "Murky crash-lands in {to}. {time}. Mrglglgl!",
		  "{time}. Murky lands, flops, and gurgles happily." } },
	{ "lurk", "Lurk", "Pretty Sure That's a Gargoyle",
		"The flight master says it's a gryphon. It's made of stone. It's definitely a gargoyle.",
		{ "Lurk doesn't flap. Lurk just glides. Nobody knows how.",
		  { "Lurk has been 'stoned' for 300 years. Literally. And also the other way, rumor has it.", "Lurk turns to stone when the sun comes up. Hope you land before dawn." },
		  "Lurk doesn't talk. Lurk stares." },
		{ "Lurk. Ride #{n}. Lurk stares. You stare back. Lurk wins.",
		  "Ride #{n}. Lurk's eyes glow faintly. Welcome back." },
		{ "Lurk lands in {to} with a sound like a falling statue. {time}.",
		  "{time}. Lurk lands and goes perfectly still. Is he okay? He's always like this." } },
},
}
