"""
Azeroth Almanac - build the data the quality-of-life helpers need (Data/QoLData.lua) from VMaNGOS.

  ns.QoL.VendorItems[itemID] = true
      Trade goods and reagents some merchant sells (thread, flux, vials, dyes, spices ...). The
      crafting calculator prices these at the vendor rather than the auction house.
  ns.QoL.DisenchantData = { mats = { [itemID] = true }, buckets = { ["quality:class:ilvl"] = { n, mat, chance, avgQty, ... } } }
      What disenchanting an item gives, by rarity (2-4), class (2 weapon, 4 armor) and item level,
      from the Classic 1.12 disenchant loot tables. n = how many items share that group.

Usage: python build_qol_data.py <mangos.sqlite> <output QoLData.lua>
"""
import sqlite3, sys, datetime, os
from collections import Counter, defaultdict
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_creatures import best_rows, PATCH


def main(db_path, out_path):
    c = sqlite3.connect(db_path)
    items = best_rows(c, 'item_template')

    # --- vendor materials
    sold = {r[0] for r in c.execute("select distinct item from npc_vendor")}
    vendor = sorted(i for i in sold if i in items and items[i]['class'] in (5, 7))

    # --- disenchanting (rows behind a condition are older alternatives, e.g. a shard before Nexus Crystals)
    table = defaultdict(list)  # entry -> rows
    for entry, item, chance, group, mn, mx in c.execute(
            "select entry,item,ChanceOrQuestChance,groupid,mincountOrRef,maxcount from disenchant_loot_template "
            "where patch_min <= ? and patch_max >= ? and condition_id = 0", (PATCH, PATCH)):
        table[entry].append((item, chance, group, mn, mx))

    def results(entry):
        rows = table.get(entry, [])
        groups = defaultdict(list)
        for r in rows:
            groups[r[2]].append(r)
        out = defaultdict(lambda: [0.0, 0.0])  # mat -> [chance, expected qty]
        for g, members in groups.items():
            explicit = sum(abs(m[1]) for m in members if m[1])
            zero = [m for m in members if not m[1]]
            share = max(100 - explicit, 0) / len(zero) if zero else 0
            for item, chance, _, mn, mx in members:
                if mn < 0:
                    continue
                p = (abs(chance) if chance else share) / 100
                out[item][0] += p
                out[item][1] += p * (mn + max(mx, mn)) / 2
        return out

    groups = defaultdict(Counter)  # "q:class:ilvl" -> Counter(disenchant entry)
    for t in items.values():
        if t['quality'] in (2, 3, 4) and t['class'] in (2, 4) and t.get('disenchant_id') and t['item_level']:
            groups[f"{t['quality']}:{t['class']}:{t['item_level']}"][t['disenchant_id']] += 1

    buckets, mats = {}, set()
    for key, entries in groups.items():
        n = sum(entries.values())
        combined = defaultdict(lambda: [0.0, 0.0])
        for entry, count in entries.items():
            for mat, (p, q) in results(entry).items():
                combined[mat][0] += p * count / n
                combined[mat][1] += q * count / n
        if not combined:
            continue
        parts = [n]
        for mat, (p, q) in sorted(combined.items(), key=lambda kv: -kv[1][0]):
            if p <= 0:
                continue
            mats.add(mat)
            parts += [mat, round(p, 4), round(q / p, 3)]
        buckets[key] = parts

    def sort_key(k):
        return tuple(int(x) for x in k.split(':'))

    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write(f"-- Generated by tools/build_qol_data.py on {datetime.date.today()} from the VMaNGOS world database\n")
        f.write("-- (github.com/vmangos/core, GPL-2.0; see Licenses\\VMaNGOS.txt). Classic 1.12 values. Do not edit by hand.\n")
        f.write("-- VendorItems: trade goods and reagents merchants sell. DisenchantData.buckets[\"quality:class:ilvl\"] =\n")
        f.write("-- { items in the group, mat, chance, average amount, ... } (class 2 weapon, 4 armor).\n")
        f.write("local _, A = ...\n")
        f.write("A.QoL = A.QoL or {}\n")
        f.write("local ns = A.QoL\n")
        f.write("ns.VendorItems = {}\n")
        f.write("for _, id in ipairs({\n")
        for i in range(0, len(vendor), 20):
            f.write("\t" + ", ".join(str(x) for x in vendor[i:i + 20]) + ",\n")
        f.write("}) do ns.VendorItems[id] = true end\n")
        f.write("ns.DisenchantData = {\n\tmats = {\n")
        for m in sorted(mats):
            name = items[m]['name'].replace('"', '\\"') if m in items else ''
            f.write(f"\t\t[{m}] = \"{name}\",\n")
        f.write("\t},\n\tbuckets = {\n")
        for k in sorted(buckets, key=sort_key):
            f.write(f"\t\t[\"{k}\"] = {{ " + ", ".join(str(x) for x in buckets[k]) + " },\n")
        f.write("\t},\n}\n")
    print(f"vendor materials: {len(vendor)}, disenchant groups: {len(buckets)}, materials: {len(mats)}")


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
