"""
Azeroth Almanac - build the hidden quest database (Data/Quests.lua) from VMaNGOS.

Only IDs and numbers, never quest text: the game itself supplies titles and text when the player
is offered a quest. The Almanac uses these records to link what the player has already met:
who starts and ends a quest, which follow-up a completed quest leads to, and which creatures,
objects and items its objectives ask for.

Usage: python build_quests.py <mangos.sqlite> <output Quests.lua>

Output:
  ns.DB.quest[questID] = { level, minLevel, zoneOrSort, "starters", "enders", "after", "targets", "items" }
    starters / enders: "npc,npc,o<object>"   who offers it / who takes it in
    after:   "quest,quest"                    quests it leads on to (chain, unlocks)
    targets: "npc:count,o<object>:count"      creatures to kill or objects to use
    items:   "item:count"                     items to bring
    races, classes: bit masks of who may take it (bit = race / class ID - 1), nil = anyone
"""
import sqlite3, sys, datetime, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_creatures import best_rows, lua, PATCH

def relations(c, table, prefix=''):
    out = {}
    for who, quest in c.execute(f"select id, quest from {table} where patch_min <= ? and patch_max >= ?", (PATCH, PATCH)):
        out.setdefault(quest, []).append(f"{prefix}{who}")
    return out

def main(db_path, out_path):
    c = sqlite3.connect(db_path)
    qt = best_rows(c, 'quest_template')

    starters = relations(c, 'creature_questrelation')
    for q, l in relations(c, 'gameobject_questrelation', 'o').items():
        starters.setdefault(q, []).extend(l)
    enders = relations(c, 'creature_involvedrelation')
    for q, l in relations(c, 'gameobject_involvedrelation', 'o').items():
        enders.setdefault(q, []).extend(l)

    after = {}
    for q, t in qt.items():
        if t['NextQuestInChain'] and t['NextQuestInChain'] in qt:
            after.setdefault(q, set()).add(t['NextQuestInChain'])
        if t['NextQuestId'] and t['NextQuestId'] > 0 and t['NextQuestId'] in qt:
            after.setdefault(q, set()).add(t['NextQuestId'])
        if t['PrevQuestId'] and t['PrevQuestId'] > 0 and t['PrevQuestId'] in qt:
            after.setdefault(t['PrevQuestId'], set()).add(q)

    lines = []
    for q in sorted(qt):
        t = qt[q]
        targets = []
        items = []
        for i in range(1, 5):
            who, n = t[f'ReqCreatureOrGOId{i}'], t[f'ReqCreatureOrGOCount{i}']
            if who:
                targets.append(f"{who}:{n}" if who > 0 else f"o{-who}:{n}")
            item, n = t[f'ReqItemId{i}'], t[f'ReqItemCount{i}']
            if item:
                items.append(f"{item}:{n}")
        row = [
            t['QuestLevel'] or None, t['MinLevel'] or None, t['ZoneOrSort'] or None,
            ",".join(starters.get(q, [])[:12]) or None,
            ",".join(enders.get(q, [])[:12]) or None,
            ",".join(str(x) for x in sorted(after.get(q, set()))[:8]) or None,
            ",".join(targets) or None,
            ",".join(items) or None,
            t['RequiredRaces'] or None, t['RequiredClasses'] or None,
        ]
        while row and row[-1] is None:
            row.pop()
        lines.append(f"[{q}]={{{','.join(lua(x) for x in row)}}},")

    header = [
        f"-- Generated by tools/build_quests.py on {datetime.date.today()} from the VMaNGOS world database",
        "-- (github.com/vmangos/core, GPL-2.0; see Licenses\\VMaNGOS.txt). Classic 1.12 records. Do not edit by hand.",
        "local _, ns = ...",
        "ns.DB = ns.DB or {}",
        "ns.DB.quest = {",
    ]
    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write("\n".join(header) + "\n" + "\n".join(lines) + "\n}\n")
    print(f"{len(lines)} quests written to {out_path}")

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
