"""
Azeroth Almanac - build the hidden item-source database (Data/Items.lua) from VMaNGOS.

Where each item comes from in the Classic 1.12 records: the creatures that drop it (with the
chance), the merchants that sell it, the quests that reward it and the objects (chests, herbs,
veins) that hold it. Only IDs and numbers: the game names everything once the player has met it,
and the Almanac shows a source only after the player has met that source.

Usage: python build_items.py <mangos.sqlite> <output Items.lua> [Lock.dbc]

Lock.dbc (optional, the client's lock table; the 3.3.5 file from github.com/Torrer/TrinityCore-3.3.5-data
holds the same Classic locks and levels) adds the skill each lock needs (0.69.0, #36 / #37):
  ns.DB.objectLock[objectID] = { skill, level }   skill 1 Lockpicking, 2 Herbalism, 3 Mining
  ns.DB.itemLock[itemID] = level                    lockboxes: the Lockpicking level

Output:
  ns.DB.item[itemID] = { droppers, "npc:chance,npc:chance", "npc,npc", "quest,quest", "object:chance,..." }
  ns.DB.object[objectID] = "Copper Vein"   (lootable objects only)
    droppers: how many kinds of creature drop it. The list keeps the 25 likeliest; an item dropped
    by more than 80 kinds is a world drop and gets no list. chance in hundredths of a percent.
"""
import sqlite3, sys, datetime, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_creatures import best_rows, loot_table, lua, PATCH

# lock types (LockType.dbc) the Almanac shows: Lockpicking, Herbalism, Mining
LOCK_SKILLS = (2, 3, 1)

def read_locks(path):
    """Lock.dbc (WDBC): id, 8 types, 8 indexes, 8 skills, 8 actions -> { lockID: { lockType: skill } }"""
    import struct
    b = open(path, 'rb').read()
    magic, n, fields, size, _ = struct.unpack('<4s4I', b[:20])
    assert magic == b'WDBC' and fields == 33, 'not a 3.3.5 / 1.12 Lock.dbc'
    locks = {}
    for i in range(n):
        r = struct.unpack('<33I', b[20 + i * size:20 + i * size + 132])
        for k in range(8):
            if r[1 + k] == 2:   # a lock type (1 would be a key item)
                locks.setdefault(r[0], {})[r[9 + k]] = r[17 + k]
    return locks

def lock_need(locks, lock_id):
    req = locks.get(lock_id, {})
    for t in LOCK_SKILLS:
        if t in req:
            return t, max(1, req[t])
    return None

def main(db_path, out_path, lock_path=None):
    c = sqlite3.connect(db_path)
    ct = best_rows(c, 'creature_template')
    gt = best_rows(c, 'gameobject_template')

    drops = {}       # item -> { npc: chance }
    loot = loot_table(c, 'creature_loot_template')
    for npc, t in ct.items():
        if not t['loot_id'] or not t['level_min']:
            continue
        for item, chance in loot.get(t['loot_id'], {}).items():
            drops.setdefault(abs(item), {})[npc] = chance

    objects = {}     # item -> { object: chance }
    oloot = loot_table(c, 'gameobject_loot_template')
    for obj, t in gt.items():
        if t['type'] in (3, 25) and t['data1']:   # chests, herbs and veins; fishing holes
            for item, chance in oloot.get(t['data1'], {}).items():
                objects.setdefault(abs(item), {})[obj] = chance

    vendors = {}     # item -> set(npc)
    by_template = {}
    for entry, item in c.execute("select entry, item from npc_vendor_template"):
        by_template.setdefault(entry, []).append(item)
    for npc, item in c.execute("select entry, item from npc_vendor"):
        vendors.setdefault(item, set()).add(npc)
    for npc, t in ct.items():
        for item in by_template.get(t.get('vendor_id') or 0, []):
            vendors.setdefault(item, set()).add(npc)

    quests = {}      # item -> set(quest)
    cols = ['entry'] + [f'RewItemId{i}' for i in range(1, 5)] + [f'RewChoiceItemId{i}' for i in range(1, 7)]
    for row in c.execute(f"select {','.join(cols)} from quest_template where patch <= ?", (PATCH,)):
        for item in row[1:]:
            if item:
                quests.setdefault(item, set()).add(row[0])

    items = set(drops) | set(objects) | set(vendors) | set(quests)
    lines = []
    for item in sorted(items):
        d = drops.get(item, {})
        dl = None
        if 0 < len(d) <= 80:
            top = sorted(d.items(), key=lambda kv: -kv[1])[:25]
            dl = ",".join(f"{npc}:{max(1, round(ch * 100))}" for npc, ch in top)
        o = objects.get(item, {})
        ol = ",".join(f"{obj}:{max(1, round(ch * 100))}" for obj, ch in sorted(o.items(), key=lambda kv: -kv[1])[:15]) or None
        v = ",".join(str(x) for x in sorted(vendors.get(item, set()))[:30]) or None
        q = ",".join(str(x) for x in sorted(quests.get(item, set()))[:20]) or None
        row = [len(d) or None, dl, v, q, ol]
        while row and row[-1] is None:
            row.pop()
        lines.append(f"[{item}]={{{','.join(lua(x) for x in row)}}},")

    header = [
        f"-- Generated by tools/build_items.py on {datetime.date.today()} from the VMaNGOS world database",
        "-- (github.com/vmangos/core, GPL-2.0; see Licenses\\VMaNGOS.txt). Classic 1.12 sources. Do not edit by hand.",
        "local _, ns = ...",
        "ns.DB = ns.DB or {}",
        "ns.DB.item = {",
    ]
    # names of lootable objects (chests, herbs, veins): the game can't name an object after the
    # fact, so the Almanac shows one of these only once the player has looted from that object
    olines = []
    for obj, t in sorted(gt.items()):
        if t['type'] in (3, 25) and t['data1'] and oloot.get(t['data1']) and t['name']:
            olines.append(f"[{obj}]={lua(t['name'])},")
    llines, ilines = [], []
    if lock_path:
        locks = read_locks(lock_path)
        for obj, t in sorted(gt.items()):
            if t['type'] == 3 and t['data1'] and oloot.get(t['data1']) and t['name']:
                need = lock_need(locks, t['data0'])
                if need:
                    llines.append(f"[{obj}]={{{need[0]},{need[1]}}},")
        for item, lock_id in c.execute("select entry, lock_id from item_template where lock_id > 0 and patch <= ? group by entry", (PATCH,)):
            need = lock_need(locks, lock_id)
            if need and need[0] == 1:
                ilines.append(f"[{item}]={need[1]},")
    with open(out_path, 'w', encoding='utf-8', newline='\n') as f:
        f.write("\n".join(header) + "\n" + "\n".join(lines) + "\n}\n")
        f.write("ns.DB.object = {\n" + "\n".join(olines) + "\n}\n")
        if llines:
            f.write("-- the skill each lootable object needs (1 Lockpicking, 2 Herbalism, 3 Mining) and its level;\n")
            f.write("-- lockboxes' Lockpicking level (Lock.dbc)\n")
            f.write("ns.DB.objectLock = {\n" + "\n".join(llines) + "\n}\n")
            f.write("ns.DB.itemLock = {\n" + "\n".join(ilines) + "\n}\n")
    print(f"{len(lines)} items written to {out_path}" + (f"; {len(llines)} object locks, {len(ilines)} lockboxes" if llines else ""))

if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2], sys.argv[3] if len(sys.argv) > 3 else None)
